### ISSUE TITLE
Replace deprecated Spring Cloud Connectors 

### ISSUE THREAD

**Issue by snicoll** [SolaceProducts/sl-spring-cloud-connectors#41]
Spring Cloud Connectors are deprecated in favour of CF JavaEnv so the integration should move as well ideally for the Spring Boot 2.2 integration

**Comment by PhilippeKhalife** [comment]
CF JavaEnv enabled project is now available https://github.com/SolaceProducts/solace-spring-boot/tree/master/solace-java-cfenv
